# Generated by Django 3.2.5 on 2021-07-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhoodapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='health_department',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='police_autorities',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
