# Generated by Django 3.2.5 on 2021-07-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhoodapp', '0002_auto_20210725_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='picture',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
