# Generated by Django 3.2.5 on 2021-07-25 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhoodapp', '0003_neighbourhood_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='police_autorities',
            new_name='police_authorities',
        ),
    ]
