# Generated by Django 3.2.5 on 2021-07-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhoodapp', '0004_rename_police_autorities_neighbourhood_police_authorities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='health_department',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='police_authorities',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
