# Generated by Django 3.2.5 on 2021-07-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhoodapp', '0005_auto_20210725_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='contact',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
